#!/bin/sh
# Sourceable library for idempotently installing/removing a macOS LaunchAgent
# that runs a single program persistently in the background.
#
# Usage:
#   . installer/launchagent.sh
#   launchagent_install pulse "$HOME/.local/bin/pulse" -config "$HOME/.config/pulse/jobs"
#   launchagent_remove pulse
#
# Unlike installer/rcblock.sh (which edits a block inside a file the user also
# owns), a LaunchAgent plist is wholly generated by us, so there's no
# "preserve unrelated content" concern here — just idempotent overwrite
# (install) and clean removal (remove). Re-running launchagent_install fully
# replaces the previous plist for that name.

launchagent_label() {
  printf 'com.gkgoat.scripts.%s' "$1"
}

launchagent_plist_path() {
  printf '%s/Library/LaunchAgents/%s.plist' "$HOME" "$(launchagent_label "$1")"
}

launchagent_log_dir() {
  printf '%s/Library/Logs/%s' "$HOME" "$(launchagent_label "$1")"
}

_launchagent_xml_escape() {
  printf '%s' "$1" | sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

# launchagent_install <name> <program> [arg...]
# Writes ~/Library/LaunchAgents/com.gkgoat.scripts.<name>.plist with
# ProgramArguments = [program, arg...], RunAtLoad, and KeepAlive on
# unsuccessful exit only (a clean exit, e.g. on `launchctl unload`, is not
# treated as a crash to restart from). stdout/stderr go under
# ~/Library/Logs/com.gkgoat.scripts.<name>/. Unloads any previous instance
# before loading the new plist, so re-running is idempotent.
launchagent_install() {
  name="$1"
  shift
  program="$1"
  shift

  label="$(launchagent_label "$name")"
  plist="$(launchagent_plist_path "$name")"
  logdir="$(launchagent_log_dir "$name")"

  mkdir -p "$(dirname "$plist")" "$logdir"

  launchctl unload "$plist" >/dev/null 2>&1 || true

  tmp="$(mktemp "${plist}.launchagent.XXXXXX")" || return 1
  {
    printf '<?xml version="1.0" encoding="UTF-8"?>\n'
    printf '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
    printf '<plist version="1.0">\n<dict>\n'
    printf '  <key>Label</key><string>%s</string>\n' "$(_launchagent_xml_escape "$label")"
    printf '  <key>ProgramArguments</key>\n  <array>\n'
    printf '    <string>%s</string>\n' "$(_launchagent_xml_escape "$program")"
    for a in "$@"; do
      printf '    <string>%s</string>\n' "$(_launchagent_xml_escape "$a")"
    done
    printf '  </array>\n'
    printf '  <key>RunAtLoad</key><true/>\n'
    printf '  <key>KeepAlive</key>\n  <dict>\n    <key>SuccessfulExit</key><false/>\n  </dict>\n'
    printf '  <key>StandardOutPath</key><string>%s/stdout.log</string>\n' "$(_launchagent_xml_escape "${logdir}")"
    printf '  <key>StandardErrorPath</key><string>%s/stderr.log</string>\n' "$(_launchagent_xml_escape "${logdir}")"
    printf '</dict>\n</plist>\n'
  } >"$tmp"
  mv "$tmp" "$plist"

  launchctl load "$plist"
}

# launchagent_remove <name>
# No-op if the plist doesn't exist.
launchagent_remove() {
  name="$1"
  plist="$(launchagent_plist_path "$name")"
  [ -f "$plist" ] || return 0

  launchctl unload "$plist" >/dev/null 2>&1 || true
  rm -f "$plist"
}
